services:
  mongodb_test:
    image: mongo:6.0
    container_name: mongodb_test
    ports:
      - "27018:27017"  # Use a different port to avoid conflicts with dev MongoDB
    environment:
      - MONGO_INITDB_DATABASE=camera_collector_test
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpassword
    volumes:
      - mongo_test_data:/data/db
      - ./scripts/mongo-init-test.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --wiredTigerCacheSizeGB 0.25 --noauth
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # Test runner service
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mongodb_test:
        condition: service_healthy
    environment:
      - MONGODB_URL=mongodb://mongodb_test:27017
      - MONGODB_DB=camera_collector_test
      - MONGODB_TEST_URL=mongodb://mongodb_test:27017
      - MONGODB_TEST_DB=camera_collector_test
      - SECRET_KEY=test_secret_key
      - ENVIRONMENT=test
      - DEBUG=True
      - BCRYPT_ROUNDS=4  # Use fewer rounds for faster tests
      - PYTHONHASHSEED=0  # For consistent hashing
    volumes:
      - .:/app
      - ./reports:/app/reports
    # Command is provided by run_tests.sh, no need to specify it here

volumes:
  mongo_test_data: